//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.Sintomatologia.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class panelEntities : DbContext
    {
        public panelEntities()
            : base("name=panelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_aSINTO_GRUPOPREGUNTA> tbl_aSINTO_GRUPOPREGUNTA { get; set; }
        public virtual DbSet<tbl_aSINTO_MENSAJES> tbl_aSINTO_MENSAJES { get; set; }
        public virtual DbSet<tbl_aSINTO_OPCIONES> tbl_aSINTO_OPCIONES { get; set; }
        public virtual DbSet<tbl_aSINTO_PREGUNTA> tbl_aSINTO_PREGUNTA { get; set; }
        public virtual DbSet<tbl_aSINTO_PROCESO> tbl_aSINTO_PROCESO { get; set; }
        public virtual DbSet<tbl_aSINTO_REGISTRO> tbl_aSINTO_REGISTRO { get; set; }
        public virtual DbSet<tbl_aSINTO_REPORTE> tbl_aSINTO_REPORTE { get; set; }
        public virtual DbSet<tbl_aSINTO_RESPUESTA> tbl_aSINTO_RESPUESTA { get; set; }
        public virtual DbSet<tbl_aSINTO_TIPOPREGUNTA> tbl_aSINTO_TIPOPREGUNTA { get; set; }
        public virtual DbSet<tbl_mSINTO_COLABORADOR> tbl_mSINTO_COLABORADOR { get; set; }
        public virtual DbSet<tbl_mSINTO_FORMULARIO> tbl_mSINTO_FORMULARIO { get; set; }
        public virtual DbSet<NPS_NUEVO_RESULTADO> NPS_NUEVO_RESULTADO { get; set; }
        public virtual DbSet<NPS_NUEVO_RESULTADO_MATRIZ> NPS_NUEVO_RESULTADO_MATRIZ { get; set; }
    
        public virtual int SP_PROCESAR_SINTOMATOLOGIA(Nullable<int> cODIGO)
        {
            var cODIGOParameter = cODIGO.HasValue ?
                new ObjectParameter("CODIGO", cODIGO) :
                new ObjectParameter("CODIGO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PROCESAR_SINTOMATOLOGIA", cODIGOParameter);
        }
    
        public virtual int USP_REPORTESINTO(Nullable<int> cODIGOREGISTRO)
        {
            var cODIGOREGISTROParameter = cODIGOREGISTRO.HasValue ?
                new ObjectParameter("CODIGOREGISTRO", cODIGOREGISTRO) :
                new ObjectParameter("CODIGOREGISTRO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_REPORTESINTO", cODIGOREGISTROParameter);
        }
    
        public virtual int SP_RegistrarNuevoNPS(string documento, string canal, string oficina, Nullable<int> vOTO, string comentario_VOTO, string cOMENTARIO_PREG2, string cOMENTARIO_PREG3)
        {
            var documentoParameter = documento != null ?
                new ObjectParameter("documento", documento) :
                new ObjectParameter("documento", typeof(string));
    
            var canalParameter = canal != null ?
                new ObjectParameter("canal", canal) :
                new ObjectParameter("canal", typeof(string));
    
            var oficinaParameter = oficina != null ?
                new ObjectParameter("oficina", oficina) :
                new ObjectParameter("oficina", typeof(string));
    
            var vOTOParameter = vOTO.HasValue ?
                new ObjectParameter("VOTO", vOTO) :
                new ObjectParameter("VOTO", typeof(int));
    
            var comentario_VOTOParameter = comentario_VOTO != null ?
                new ObjectParameter("comentario_VOTO", comentario_VOTO) :
                new ObjectParameter("comentario_VOTO", typeof(string));
    
            var cOMENTARIO_PREG2Parameter = cOMENTARIO_PREG2 != null ?
                new ObjectParameter("COMENTARIO_PREG2", cOMENTARIO_PREG2) :
                new ObjectParameter("COMENTARIO_PREG2", typeof(string));
    
            var cOMENTARIO_PREG3Parameter = cOMENTARIO_PREG3 != null ?
                new ObjectParameter("COMENTARIO_PREG3", cOMENTARIO_PREG3) :
                new ObjectParameter("COMENTARIO_PREG3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarNuevoNPS", documentoParameter, canalParameter, oficinaParameter, vOTOParameter, comentario_VOTOParameter, cOMENTARIO_PREG2Parameter, cOMENTARIO_PREG3Parameter);
        }
    }
}
