//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.NPS.BE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class panelEntities : DbContext
    {
        public panelEntities()
            : base("name=panelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NPS_NUEVO_RESULTADO> NPS_NUEVO_RESULTADO { get; set; }
        public virtual DbSet<NPS_NUEVO_RESULTADO_MATRIZ> NPS_NUEVO_RESULTADO_MATRIZ { get; set; }
    
        public virtual int SP_RegistrarNuevoNPS(string documento, string canal, string oficina, Nullable<int> vOTO, string comentario_VOTO, string cOMENTARIO_PREG2, string cOMENTARIO_PREG3)
        {
            var documentoParameter = documento != null ?
                new ObjectParameter("documento", documento) :
                new ObjectParameter("documento", typeof(string));
    
            var canalParameter = canal != null ?
                new ObjectParameter("canal", canal) :
                new ObjectParameter("canal", typeof(string));
    
            var oficinaParameter = oficina != null ?
                new ObjectParameter("oficina", oficina) :
                new ObjectParameter("oficina", typeof(string));
    
            var vOTOParameter = vOTO.HasValue ?
                new ObjectParameter("VOTO", vOTO) :
                new ObjectParameter("VOTO", typeof(int));
    
            var comentario_VOTOParameter = comentario_VOTO != null ?
                new ObjectParameter("comentario_VOTO", comentario_VOTO) :
                new ObjectParameter("comentario_VOTO", typeof(string));
    
            var cOMENTARIO_PREG2Parameter = cOMENTARIO_PREG2 != null ?
                new ObjectParameter("COMENTARIO_PREG2", cOMENTARIO_PREG2) :
                new ObjectParameter("COMENTARIO_PREG2", typeof(string));
    
            var cOMENTARIO_PREG3Parameter = cOMENTARIO_PREG3 != null ?
                new ObjectParameter("COMENTARIO_PREG3", cOMENTARIO_PREG3) :
                new ObjectParameter("COMENTARIO_PREG3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarNuevoNPS", documentoParameter, canalParameter, oficinaParameter, vOTOParameter, comentario_VOTOParameter, cOMENTARIO_PREG2Parameter, cOMENTARIO_PREG3Parameter);
        }
    
        public virtual ObjectResult<SP_ConsultarNuevoMartrizNPS_Result> SP_ConsultarNuevoMartrizNPS(Nullable<int> iDRESULTADO)
        {
            var iDRESULTADOParameter = iDRESULTADO.HasValue ?
                new ObjectParameter("IDRESULTADO", iDRESULTADO) :
                new ObjectParameter("IDRESULTADO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ConsultarNuevoMartrizNPS_Result>("SP_ConsultarNuevoMartrizNPS", iDRESULTADOParameter);
        }
    
        public virtual ObjectResult<SP_NPSConsultarUltimoRegistroPorId_Result> SP_NPSConsultarUltimoRegistroPorId(string documento)
        {
            var documentoParameter = documento != null ?
                new ObjectParameter("documento", documento) :
                new ObjectParameter("documento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NPSConsultarUltimoRegistroPorId_Result>("SP_NPSConsultarUltimoRegistroPorId", documentoParameter);
        }
    
        public virtual int SP_RegistrarNuevoMartrizNPS(Nullable<int> iDRESULTADO, Nullable<int> idpregunta, Nullable<int> idtipo_respuesta)
        {
            var iDRESULTADOParameter = iDRESULTADO.HasValue ?
                new ObjectParameter("IDRESULTADO", iDRESULTADO) :
                new ObjectParameter("IDRESULTADO", typeof(int));
    
            var idpreguntaParameter = idpregunta.HasValue ?
                new ObjectParameter("idpregunta", idpregunta) :
                new ObjectParameter("idpregunta", typeof(int));
    
            var idtipo_respuestaParameter = idtipo_respuesta.HasValue ?
                new ObjectParameter("idtipo_respuesta", idtipo_respuesta) :
                new ObjectParameter("idtipo_respuesta", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarNuevoMartrizNPS", iDRESULTADOParameter, idpreguntaParameter, idtipo_respuestaParameter);
        }
    }
}
